# Generated by Django 3.0.2 on 2020-05-01 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_questiom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_answer', models.CharField(max_length=30)),
                ('name_person_answer', models.CharField(max_length=30)),
                ('theme_question_answer', models.CharField(max_length=100)),
                ('full_text_answer', models.CharField(max_length=2000)),
                ('full_text_answer_old', models.CharField(max_length=2000)),
                ('created_time_quest_old', models.CharField(max_length=50)),
                ('created_time_quest_answer', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
