# Generated by Django 3.0.5 on 2020-04-27 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=1)),
                ('text_quest', models.TextField(max_length=500)),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
